services:
  - type: web
    name: rent-backend
    runtime: python
    plan: free
    region: frankfurt

    # Specify Node.js version for Playwright
    nodeVersion: "20"

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    postDeployCommand: |
      playwright install --with-deps chromium

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: SCRAPERAPI_KEY
        sync: false
