services:
  - type: web
    name: rent-backend
    runtime: python
    plan: free
    region: frankfurt

    buildCommand: |
      pip install -r requirements.txt

    postDeployCommand: |
      playwright install chromium

    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: SCRAPERAPI_KEY
        sync: false
