services:
  - type: web
    name: rent-backend
    runtime: python
    plan: free
    region: frankfurt

    buildCommand: |
      pip install -r requirements.txt

    postDeployCommand: |
      playwright install --with-deps chromium

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: SCRAPERAPI_KEY
        sync: false

